### ISSUE TITLE
Add dim Color Mode

### ISSUE THREAD

**Issue by ronilaukkarinen** [elk-zone/elk#1723]
I prefer "dim" color schemes for many dark themes, in my opinion `#111` or `17, 17, 17` rgb is a bit too dark.

Here's a quick proof of concept "Dim" Color Mode which uses the default Mastodon web UI background `rgb(25, 27, 34)`. This could be a setting "Dim" like on Twitter.

Before:
![elk mementomori social_settings_interface (1)](https://user-images.githubusercontent.com/1534150/218306478-634d14a6-56f7-46c1-91da-97c6401027e2.png)

After:
![elk mementomori social_home](https://user-images.githubusercontent.com/1534150/218306454-28ab1e53-7633-4d00-ae79-a93d6f7d6a34.png)

![elk mementomori social_settings_interface (2)](https://user-images.githubusercontent.com/1534150/218306558-31ada209-8c8a-4ac4-a6c1-f15a76ef98de.png)

**Comment by Nive9** [comment]
I agree, and maybe the [Catppuccin colour scheme](https://github.com/catppuccin/elk) would be an option?

**Comment by ronilaukkarinen** [comment]
> I agree, and maybe the [Catppuccin colour scheme](https://github.com/catppuccin/elk) would be an option?

That looks really nice! Didn't know there's already a dim-ish themes out there for Elk.

**Comment by theotherlinh** [comment]
definitely agree with a dim mode. I'd go a notch lighter still, but anything works :)

**Comment by ronilaukkarinen** [comment]
Here are the CSS variables, this uses the official colors from the default Mastodon UI , I kinda like them.

```css
:root {
  --c-bg-base: #191b22;
  --rgb-bg-base: 25, 27, 34;
  --c-border: rgba(45, 53, 56, .44);
  --c-bg-active: rgba(85, 93, 100, .18);
}
````

You can test them out for instance by using [Live editor](https://addons.mozilla.org/en-US/firefox/addon/live-editor-for-css-less-sass/) (for both Chrome and Firefox) and pinning the styles with the pin icon.

![image](https://user-images.githubusercontent.com/1534150/219879055-cdf1ba04-45b1-4c15-b6e1-69f07d851d43.png)

I'm not exactly sure how to create a selection for this, but if anyone is not already attempting this, I could try and send a PR later.

**Comment by ronilaukkarinen** [comment]
I have not yet figured out a way to fix "Show more" button as it desaturates the background. So I'm just forcing the styles without the filter.

Current process to add these to a canary build:

1. Get latest build
2. `nano $HOME/elk/styles/global.css`
3. Add to first line:

```css
:root {
  --c-bg-base: #191b22;
  --rgb-bg-base: 25, 27, 34;
  --c-border: rgba(45, 53, 56, .44);
  --c-bg-active: rgba(85, 93, 100, .18);
}

/* Fix "Show more" button background color */
button.filter-saturate-0:not(:hover) {
  color: #858585;
  filter: unset;
}
```

4. Replace `#111111` with `#191b22` to get mobile PWA header and status bar to the right color:

```shell
nano $HOME/elk/modules/pwa/i18n.ts
nano $HOME/elk/plugins/color-mode.ts
```

5. Rebuild
