### ISSUE TITLE
Alt text is too wide

### ISSUE THREAD

**Issue by Christopher-Hayes** [elk-zone/elk#2890]
## Description

Alt text on desktop screens is really wide, it's not good for readability.

## Screenshots

![image](https://github.com/elk-zone/elk/assets/6013871/48e9ac14-6cec-4b26-855a-9dfee7dc3a70)

![image](https://github.com/elk-zone/elk/assets/6013871/719ca779-4e37-4d37-a73a-17f0a5377e00)

## Proposed Solution

If we match the max-width of Mastodon posts (600px), we get:

![image](https://github.com/elk-zone/elk/assets/6013871/fe6b7bca-d5ab-4168-b605-f09b03e3c1a5)

![image](https://github.com/elk-zone/elk/assets/6013871/d7839f8d-7a8d-4969-8036-777a179e44df)

For longer alt text (like the 2nd screenshot), we could clamp it at 3 lines:

![image](https://github.com/elk-zone/elk/assets/6013871/a193e6e0-cf95-4140-b657-c50a99c9755f)

### Code from proposed solution

Parent div:

```css
max-width: 600px;
border-radius: 12px; /* full rounded doesn't look good on multiple lines */
```

Alt text p:

```css
[line-clamp-3] {
  display: -webkit-box;
  overflow: hidden;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
}
```
