### ISSUE TITLE
NUXT_PUBLIC_* environment variables not working

### ISSUE THREAD

**Issue by pro-sumer** [elk-zone/elk#2997]
I'm hosting my own Elk instance and in my `docker-compose.yaml` file I have this:

```
  elk:
    hostname: elk
    environment:
      - NUXT_PUBLIC_DEFAULT_SERVER=my.domain.com
      - NUXT_PUBLIC_SINGLE_INSTANCE=true
    container_name: elk
    image: ghcr.io/elk-zone/elk
    restart: always
    volumes:
      - './elk-storage:/elk/data'
    ports:
      - 5314:5314
    networks:
      - external_network
```

However, I still get the local timeline of m.webtoo.ls and when I click on "Sign in" I can type in a Mastodon Server Address, so it looks like both environment variables are being ignored.

(Or is my setup incorrect?)
