### ISSUE TITLE
"Cannot connect to the server" on self-hosted Elk instance

### ISSUE THREAD

**Issue by pro-sumer** [elk-zone/elk#2999]
I'm trying to set up a self-hosted Elk instance for my self-hosted Mastodon instance.

It seemed to work one single day, but since then I get this error when trying to connect to any/my Mastodon Server Address:

```
Cannot connect to the server.
```

Note: I already set up the ./elk-storage for user/group 911:911:

```
  elk:
    hostname: elk
    container_name: elk
    image: ghcr.io/elk-zone/elk
    restart: always
    volumes:
      - './elk-storage:/elk/data'
    ports:
      - 5314:5314
    networks:
      - external_network
```
